### ISSUE TITLE
VkPipelineMatchControl in list of deviations

### ISSUE THREAD

**Issue by etomzak** [KhronosGroup/VulkanSC-Docs#3]
Since Vulkan SC adds the `VkPipelineMatchControl` enum type, should it be added to the "Additions" list in Appendix H?

For comparison, `VkPipelineCacheValidationVersion` is another enum type that's added by Vulkan SC, and it *is* listed in Appendix H.

**Comment by dgkoch** [comment]
This is a reasonable request. I've queued up a fix for the next release.

**Comment by dgkoch** [comment]
This has been addressed in the 1.0.12 spec update.
