### ISSUE TITLE
deviceNoDynamicHostAllocations and pAllocator

### ISSUE THREAD

**Issue by etomzak** [KhronosGroup/VulkanSC-Docs#5]
The spec allows `VkPhysicalDeviceVulkanSC10Properties::deviceNoDynamicHostAllocations` to be `VK_FALSE` --- i.e., a conformant implementation of Vulkan SC is allowed to dynamically allocate memory. However, section 11.1 states that all pointers to `VkAllocationCallbacks` must be `NULL`. This seems strange, because it means that a safety-certified application could theoretically use a Vulkan SC implementation that allocates dynamic memory, but there is no way for the application to provide custom allocators.

Is there an explanation for this design decision anywhere?

Also, is there a reason that `VkAllocationCallbacks` isn't removed from Vulkan SC?

**Comment by dgkoch** [comment]
The theoretical Vulkan SC implementation that allocates dynamic memory would just do the allocation directly (ie no custom allocator support), as it states in section 11.1:

> The Vulkan SC implementation will perform its own host memory allocations. Support for application-provided memory allocation, as supported in Base Vulkan, has been removed in Vulkan SC.



> Is there an explanation for this design decision anywhere?

Callbacks are generally not desired in safety certified code. 

> Also, is there a reason that VkAllocationCallbacks isn't removed from Vulkan SC?

The type is used in the command signature of all create/destroy methods and we didn't want to change the command signatures and break compatibility with Vulkan.

**Comment by etomzak** [comment]
Makes sense. Thanks!
