### ISSUE TITLE
VkDebugReportObjectTypeEXT in deviations

### ISSUE THREAD

**Issue by etomzak** [KhronosGroup/VulkanSC-Docs#6]
Appendix H, under Removals, Resource Descriptors, removes `VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR_EXT`. Given that `VkDebugReportObjectTypeEXT`, the extension that adds this enum value, is not on the list of extensions supported by Vulkan SC, is this line necessary? There don't seem to be any other references to `VkDebugReportObjectTypeEXT` in the Vulkan SC spec.

**Comment by dgkoch** [comment]
Agreed - I'll propose a change to remove them in the next spec update.

**Comment by dgkoch** [comment]
This has been addressed in the 1.0.12 spec update.
